name: Zofia Korcz
description: Personal site of Zofia Korcz - front-end developer and amateur HTML5 game maker
url: http://zofiakorcz.pl
markdown: redcarpet
pygments: true
permalink: /:title
port: 4000
safe: true
