name: Zofia Korcz
description: Personal site of Zofia Korcz - front-end developer and amateur HTML5 game maker
url: https://zofiakorcz.pl
markdown: kramdown
highlighter: rouge
permalink: /:title
port: 4000
safe: true
